title: Titulazo
author: Pablo Alonso Flores
email: alu0101209500@ull.edu.es
description: > # this means to ignore newlines until "baseurl:"
  No hay mucho que describir

# social links
twitter_username: AlonsodeLugo # DO NOT include the @ character, or else the build will fail!
github_username:  alu0101209500 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
